steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sameer/shaout:$REVISION_ID', '.' ]
- name: 'busybox'
  args: [ 'echo', 'revision: $REVISION_ID' ]
images:
- 'gcr.io/$PROJECT_ID/sameer/shaout'
tags:
- 'shaout'