steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sameer/shaout:$REVISION_ID', '-t', 'gcr.io/$PROJECT_ID/sameer/shaout:latest', '.' ]
images:
- 'gcr.io/$PROJECT_ID/sameer/shaout'
tags:
- 'shaout'