version: 2

jobs:
  prepare-source:
    docker:
      - image: cimg/go:1.13
    working_directory: /home/circleci/go/src/github.com/sameersbn/shaout
    steps:
      - checkout
      - run: make mod-download
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /home/circleci/go/

  build:
    docker:
      - image: cimg/go:1.13
    working_directory: /home/circleci/go/src/github.com/sameersbn/shaout
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: make build

  test:
    docker:
      - image: cimg/go:1.13
    working_directory: /home/circleci/go/src/github.com/sameersbn/shaout
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: make fmt-test
      - run: make vet
      - run: GOTEST=gotestsum GOTESTSUM_JUNITFILE=unit-tests.xml make test
      - store_test_results:
          path: .

  publish-image:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: /home/circleci/go/src/github.com/sameersbn/shaout
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: |
          echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
      - run: gcloud builds submit --config cloudbuild.yaml --substitutions COMMIT_SHA=${CIRCLE_SHA1},_IMAGE_TAG=${CIRCLE_TAG:-latest},_APP_VERSION=$(git describe --tags --always)

workflows:
  version: 2

  build-test-and-publish:
    jobs:
      - prepare-source
      - build:
          requires:
            - prepare-source
      - test:
          requires:
            - prepare-source
      - publish-image:
          requires:
            - build
            - test
          filters:
            branches:
              only: circle-ci
