version: 2

jobs:
  checkout_code:
    docker:
      - image: cimg/go:1.13
    working_directory: ~/go/src/github.com/sameersbn/shaout
    steps:
      - checkout
      - run:
          name: Fetch go modules
          command: make mod-download
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/go/

  build:
    docker:
      - image: cimg/go:1.13
    working_directory: ~/go/src/github.com/sameersbn/shaout
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "Build"
          command: make build

  test:
    docker:
      - image: cimg/go:1.13
    working_directory: ~/go/src/github.com/sameersbn/shaout
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "Vet"
          command: make vet
      - run:
          name: "Test"
          command: make test

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
