version: 2.1

orbs:
  go: circleci/go@1.1.1

jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/mod-download-cached
      - run: make build

  test:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/mod-download-cached
      - run:
          name: Run fmt test
          command: make fmt-test
      - run:
          name: Run vet check
          command: make vet
      - run:
          name: Run tests
          command: |
            export OUTPUT_DIR=/tmp/tests/
            mkdir -p ${OUTPUT_DIR} && make test
      - store_test_results:
          path: /tmp/tests
      - run:
          name: Generate coverage report
          command: |
            export OUTPUT_DIR=/tmp/artifacts/
            mkdir -p ${OUTPUT_DIR} && make coverage
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  build_and_test:
    jobs:
      - build
      - test
