version: 2

jobs:
  build:
    working_directory: /go/src/github.com/sameersbn/shaout
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run:
          name: Build
          command: make build

  test:
    docker:
      - image: cimg/go:1.13
    steps:
      - run:
          name: Commit
          command: echo "$CIRCLE_SHA1"
      - run:
          name: Stage
          command: echo "$CIRCLE_STAGE"
      - run:
          name: Test step 3
          command: echo "Executing test step 3"

  release:
    docker:
      - image: cimg/go:1.13
    steps:
      - run:
          name: Release step 1
          command: echo "Release step 1"
      - run:
          name: Release step 2
          command: echo "Release step 2"
      - run:
          name: Release step 3
          command: echo "Release step 3"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
