version: 2.1

orbs:
  go: circleci/go@1.1.1
  gcp-cli: circleci/gcp-cli@1.8.4
  codecov: codecov/codecov@1.0.5
  github-release: h-matsuo/github-release@0.1.3

jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/mod-download-cached
      - run: make build

  test:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/mod-download-cached
      - run:
          name: Run fmt test
          command: make fmt-test
      - run:
          name: Run vet check
          command: make vet
      - run:
          name: Run tests
          command: mkdir -p ${OUTPUT_DIR} && make test
          environment:
            OUTPUT_DIR: /tmp/test-results/
      - store_test_results:
          path: /tmp/test-results/
      - run:
          name: Generate coverage report
          command: mkdir -p ${OUTPUT_DIR} && make coverage
          environment:
            OUTPUT_DIR: /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts/
      - codecov/upload:
          file: c.out

  publish:
    executor:
      name: github-release/default
    steps:
      - run:
          name: Generate fake artifacts
          command: |
            mkdir -p /tmp/dist/
            echo "shaout-linux-amd64" > /tmp/dist/shaout-linux-amd64
            echo "shaout-darwin-amd64" > /tmp/dist/shaout-darwin-amd64
      - run:
          name: List files
          command: ls -la /tmp/dist/
      - github-release/create:
          tag: ${CIRCLE_TAG}
          file-path: /tmp/dist/
          title: Shaout ${CIRCLE_TAG}
          description: $(git cat-file -p ${CIRCLE_TAG} | sed '/-----BEGIN PGP SIGNATURE-----/,//d' | tail -n +6)

  publish-image:
    executor:
      name: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          name: Building image
          command: gcloud builds submit --config cloudbuild.yaml --substitutions COMMIT_SHA=${CIRCLE_SHA1},TAG_NAME=${CIRCLE_TAG:-$(git describe --tags --always)},_IMAGE_TAG=${CIRCLE_TAG:-latest}

workflows:
  build-test-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
      - test:
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
      - publish-image:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              only: master
      - publish:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/

