version: 2
jobs:
  build:
    working_directory: /go/src/github.com/sameersbn/ghr-debug
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run:
          name: Build binaries
          command: |
            count=0
            while [[ $count -lt 10 ]]; do
              echo "Building ($count)..."
              count=$(expr $count + 1)
              sleep 1
            done
            echo '#!/bin/bash' >shaout
            echo "echo ${CIRCLE_SHA1}" >shaout
            chmod +x shaout
      - persist_to_workspace:
          root: /go/src/github.com/sameersbn/ghr-debug
          paths:
            - shaout

  release:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Install github-release"
          command: go get github.com/aktau/github-release
      - run:
          name: "Publish Release on GitHub"
          command: |
            github-release delete -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} 2>/dev/null ||:
            github-release release -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} -d "ghr-debug release ${CIRCLE_TAG}"
      - run:
          name: "Upload Release artifacts"
          command: |
            for f in $(find /tmp/artifacts/ -type f)
            do
              github-release upload -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} -n "$(basename ${f})" -f "${f}"
            done

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
