version: 2

jobs:
  build:
    working_directory: /home/circleci/go/src/github.com/sameersbn/shaout
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run:
          name: "Build"
          command: make build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
