version: 2.1

orbs:
  go: circleci/go@1.1.1

jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/mod-download-cached

workflows:
  main:
    jobs:
      - build
