version: 2

jobs:
  build:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run:
          name: Build Step 1
          command: echo "Executing build step 1..."
      - run:
          name: Build Step 2
          command: echo "Executing build step 2..."
      - run:
          name: Build Step 3
          command: echo "Executing build step 3..."

  test:
    docker:
      - image: cimg/go:1.13
      - run:
          name: Test step 1
          command: echo "Executing test step 1"
      - run:
          name: Test step 2
          command: echo "Executing test step 2"
      - run:
          name: Test step 3
          command: echo "Executing test step 3"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
